AJS.toInit(function(b){function e(a){AJS.trigger("analytics",{name:"confluence.quick.create.blank.click"})}function p(a){if(-1==window.location.href.indexOf("src\x3dquick-create"))a.on("click",function(){g()});else b.getJSON(AJS.contextPath()+"/rest/create-dialog/1.0/storage/quick-create",function(c){c.isExist||h(a)})}function h(a){var c=new AJS.InlineDialog(b("#create-page-button"),"discoveryTooltip",function(a,c,b){a.html(Confluence.Quick.Create.discoveryTooltip());b();AJS.trigger("analytics",{name:"confluence.quick.create.discovery.open"})},
{gravity:"s",width:270,noBind:!0,persistent:!0});c.show();b(document).off("click","#closeDisDialog").on("click","#closeDisDialog",function(){AJS.trigger("analytics",{name:"confluence.quick.create.discovery.close"});c.hide();g()});a.on("click",function(){c.hide();g()})}function g(){b.ajax({url:AJS.contextPath()+"/rest/create-dialog/1.0/storage/quick-create",type:"PUT"})}Confluence.Blueprint=Confluence.Blueprint||{};var m=!1,f,k=AJS.Meta.get("space-key");Confluence.Blueprint.Dialog=Confluence.Dialogs.CreateDialogBase({dialogId:"create-dialog",
webItemsPath:"/rest/create-dialog/1.0/blueprints/web-items",helpLinkTemplate:Confluence.Templates.Blueprints.helpLink,headingText:AJS.I18n.getText("create.content.plugin.create-dialog.header.create.label")});Confluence.Blueprint.loadDialog=function(a){var c=AJS.$.Deferred();f&&(a=AJS.$.extend(a,{errorMessage:f}));if(m)c.resolve(Confluence.Blueprint.Dialog.openDialog(a));else{var b=Confluence.Blueprint.Dialog.openDialog(a);var e=WRM.require("wrc!create-content"),d=AJS.$.Deferred();Confluence.Blueprint.Dialog.requestSpaces().done(function(){var a=
Confluence.Blueprint.Dialog.loadedSpaces;Confluence.Blueprint.Dialog.requestWebItems((a.promotedSpaces.spaces[0]||a.otherSpaces.spaces[0]).id).done(function(){d.resolve()}).fail(function(a){d.resolve(a)})}).fail(function(a){d.resolve(a)});AJS.$.when(d.promise(),e).done(function(d){AJS.trigger("blueprint.wizard-register.load");Confluence.Dialogs.LocationPanel(Confluence.Blueprint.Dialog);a=AJS.$.extend(a,{createDialog:b,dialogBase:Confluence.Blueprint.Dialog});if(d)try{"READ_ONLY"===JSON.parse(d.responseText).errorType&&
(f=AJS.I18n.getText("read.only.mode.default.error.short.message"))}catch(q){f=AJS.I18n.getText("server.error.message")}finally{a=AJS.$.extend(a,{errorMessage:f})}m=!0;c.resolve(Confluence.Blueprint.Dialog.openDialog(a))}).fail(function(){AJS.log("Could not load resources for create dialog.")})}return c.promise()};var n=!1;AJS.bind("blueprint.wizard-register.load",function(){n||(AJS.trigger("blueprint.wizard-register.ready"),n=!0)});var d=b("#create-page-button:visible"),l=!1;d.length&&(d.click(function(a){l?
(l=!1,a=(a=b(a.target).closest("a").attr("href"))&&-1!=a.indexOf("createpage.action")?!1:!0):a=!0;if(a)return AJS.trigger("analytics",{name:"confluence.quick.create.dialog.open"}),Confluence.Blueprint.loadDialog({triggerSrc:"create-page"}),!1}).mousedown(function(a){var c=a.which||a.button;if(b.browser.mozilla&&2==c||3==c)c=0;l=0!==c&&1!==c||a.ctrlKey||a.altKey||a.shiftKey||a.metaKey}),function(a){var c=AJS.Meta.get("content-type"),d=AJS.Meta.get("content-id")||AJS.Meta.get("page-id"),e=AJS.contextPath()+
"/pages/createpage.action";k?(c="page"==c?e+"?"+b.param({spaceKey:k,fromPageId:d}):e+"?"+b.param({spaceKey:k}),a.attr("href",c)):a.attr("href","#")}(d),b(document).on("click",".create-child-page-link",function(){Confluence.Blueprint.loadDialog({location:"child-page"});return!1}),b("#addPageLink, #addBlogLink, .acs-pagetree-create-link").hide(),function(a){var c=b("#quick-create-page-button");c.length?c.is(":visible")&&(p(a),c.on("click",e)):a.removeClass("clc-create-dialog-btn").find("span").removeClass()}(d),
function(){var a=window.location.pathname;-1<a.indexOf("/draft-createpage.action")?AJS.bind("rte-ready",function(a){b("#rte-button-publish").click(function(){AJS.trigger("analytics",{name:"confluence.quick.create.create-dialog.blue-print.save"})});b("#rte-button-cancel").click(function(){AJS.trigger("analytics",{name:"confluence.quick.create.create-dialog.blue-print.close"})})}):-1<a.indexOf("/createpage.action")&&(a=b("#createpageform input[name\x3d'queryString']").val(),"string"===typeof a&&-1<
a.indexOf("src\x3dquick-create")?AJS.bind("rte-ready",function(a){b("#rte-button-publish").click(function(){AJS.trigger("analytics",{name:"confluence.quick.create.blank.save"})});b("#rte-button-cancel").click(function(){AJS.trigger("analytics",{name:"confluence.quick.create.blank.close"})});b("#rte-button-location").click(function(){AJS.trigger("analytics",{name:"confluence.quick.create.blank.change.location"})})}):AJS.bind("rte-ready",function(a){b("#rte-button-publish").click(function(){AJS.trigger("analytics",
{name:"confluence.quick.create.create-dialog.blank.save"})});b("#rte-button-cancel").click(function(){AJS.trigger("analytics",{name:"confluence.quick.create.create-dialog.blank.close"})})}))}(),b("#quick-create-page-button").is(":visible")?AJS.whenIType("c").followLink("#quick-create-page-button"):AJS.whenIType("c").click("#create-page-button"))});
AJS.bind("shortcuts-loaded.keyboardshortcuts",function(b,e){AJS.$.each(e.shortcuts,function(b,h){if("#createPageLink"==h.param)return e.shortcuts.splice(b,1),!1})});