define("confluence-labels/labels/labels","ajs confluence/legacy window document jquery confluence/message-controller".split(" "),function(d,q,w,x,b,y){var m,r=function(a,e){if(!a||!e)var c=b("#dialog-label-list"),a=c.attr("entityid"),e=c.attr("entitytype");return!a||!e?b(k.labelView):b(".labels-section-content").filter(function(){return this.getAttribute("entityid")===a&&this.getAttribute("entitytype")===e}).find(k.labelView)};d.bind("init.rte-control",function(){var a=0;if(d.Meta.get("num-labels"))a=
d.Meta.get("num-labels");else if(b("#createPageLabelsString").val())a=b.trim(b("#createPageLabelsString").val()).split(/\s+/).length;if(a!==0){d.Meta.set("num-labels",a);b("#rte-button-labels").trigger("updateLabel")}});var z=function(a){a=b.trim(a);if(!a)return[];var e=[],c=(new Date).getTime();b(a.split(/\s+/)).each(function(a,b){var h=b.split(":"),i,d=h[0];if(h.length===2){i=h[0];d=h[1]}e.push({name:d,prefix:i,id:c});c++});return e},k={labelView:".label-list",labelItem:".aui-label",noLabelsMessage:".no-labels-message",
idAttribute:"data-label-id",labelsFormFieldId:d.Meta.get("labels-form-field-id")||"createPageLabelsString"},A=d.contextPath(),o={base:A+"/rest/ui/1.0/",getRestEndPoint:function(a){return this.base+(a==="attachment"||a==="template"||a==="space"?a+"/":"content/")},index:A+"/labels/autocompletelabel.action?maxResults=3",validate:function(){return this.getRestEndPoint()+"labels/validate"},add:function(a,b){return this.getRestEndPoint(a)+b+"/labels"},remove:function(a,b,c){return this.getRestEndPoint(a)+
b+"/label/"+c},list:function(a,b){return this.getRestEndPoint(a)+b+"/labels"}},s=function(a){var d=b("#"+k.labelsFormFieldId);d.length&&d.val(a)},t=function(){var a=b("#"+k.labelsFormFieldId);return a.length?a.val():""},u=function(){return b(".space-administration").length},l=function(a){return a==="0"||!!x.getElementById("createpagetemplate")},B=function(a){p();if(a&&a.promise){a.always([C,D]);a.done(function(a,c){d.Meta.set("num-labels",r().first().find(k.labelItem).size());b("#rte-button-labels").trigger("updateLabel");
var g=c.not(".editable");c.find(".aui-label").length===0?g.find(".labels-edit-container").before(q.Templates.Labels.nolabels()):g.find(".no-labels-message").remove()})}return a},D=function(){b("#labels-string, #add-labels-editor-button").removeAttr("disabled aria-disabled")},C=function(){b("#labels-string").val("")},p=function(a){a=a||null;b("#label-operation-error-message").empty().toggle(!!a);d.messages.error("#label-operation-error-message",{body:a})};b(x).on("click",".label-list.editable .aui-icon-close",
function(a){a.preventDefault();a=b("#dialog-label-list");m.removeLabel(b(this).closest("li"),a.attr("entityid"),a.attr("entitytype"))});d.toInit(function(){if(u()){m.bindAutocomplete();b(".label-list").addClass("editable")}});d.bind("editor-heartbeat",function(a,e){if(typeof e.labelsHash!=="undefined"){var c=b("#rte-button-labels");if(c.data("labelsHash")!==e.labelsHash){var g=d.Meta.get("content-type"),f=q.Editor.Drafts.isNewContent()?d.Meta.get("draft-id"):d.Meta.get("page-id");l(f)||b.ajax({url:o.list(g,
f),cache:false,success:function(a){d.Meta.set("num-labels",a.labels.length);b("#rte-button-labels").trigger("updateLabel");m.updateDialogLabelList(a.labels)},error:function(a,b){d.logError(b)}});c.data("labelsHash",e.labelsHash)}}});return m={addLabel:function(a,e,c){if(a){b("#labels-string, #add-labels-editor-button").attr({disabled:"disabled","aria-disabled":true});if(l(e)){var a=(t()+" "+a).split(/\s+/),g=[];b.each(a,function(a,c){b.inArray(c,g)===-1&&g.push(c)});a=g.join(" ")}var a={url:l(e)?
o.validate():o.add(c,e),type:"POST",dataType:"json",contentType:"application/json",data:JSON.stringify(z(a))},f=b.Deferred(),a=b.ajax(a);a.done(function(a){var g=b("#dialog-label-list").find(".label-list"),a=a.labels,j,v=[];b.each(a,function(a,b){b.prefix&&b.prefix!=="global"?v.push(b.prefix+":"+b.name):v.push(b.name)});j=v.join(" ");if(l()){var E=(new Date).getTime();b.each(a,function(a,b){b.id=E++})}s(j);m.updateDialogLabelList(a);j=d.Meta.get("space-key");var n=r(e,c).not(".editable");if(n.length){n.find("li.aui-label").remove();
n.find("li.labels-edit-container").before(q.Templates.Labels.dialogLabels({labels:a,spaceKey:j}))}f.resolve(a,n.add(g))});a.fail(function(a,b){var c;if(b==="timeout")c=d.I18n.getText("xhr.timeout");else if(a.status===405)c=y.parseError(a);else try{c=JSON.parse(a.responseText).message}catch(g){c=b;d.log("Unexpected error when adding labels: "+g.message)}d.log("Failed to add labels: "+c);d.log("Failed to add labels xhr: "+a.responseText);p(c);f.reject(b)});a=f.promise()}else a=b.Deferred().reject();
return B(a)},removeLabel:function(a,e,c){var g=a,f=e,h=c;if(g){g=g.jquery?g:b(g);if(u()){f=d.Meta.get("space-key");h="space"}var i=g.attr(k.idAttribute),j=b.Deferred();if(l(f)){a=b.Deferred();a.resolve()}else{a={url:o.remove(h,f,i),type:"DELETE",dataType:"json",contentType:"application/json",data:{}};a=b.ajax(a)}a.done(function(){var a=u()?b("#space-categories-list"):r(f,h),c=a.find(k.labelItem).filter("["+k.idAttribute+"='"+i+"']");c.fadeOut("normal",function(){c.remove();j.resolve(g,a)});var d=
b.trim(g.find("a").text()),e=t().split(/\s+/),e=b.grep(e,function(a){return a&&a!==d});s(e.join(" "))});a.fail(function(a,b){var c;c=b==="timeout"?d.I18n.getText("xhr.timeout"):y.parseError(a,b);d.log("Failed to remove label: "+c);d.log("Failed to remove label xhr: "+a.responseText);p(c);j.reject(b)});a=j.promise()}else a=false;return B(a)},bindAutocomplete:function(){var a=b("#labels-string"),e=a.parents("#add-labels-form").length;if(a.length){b(w).bind("quicksearch.ajax-success",function(a,b){if(b.url===
"/labels/autocompletelabel.action?maxResults=3"){m.queryTokens=b.json&&b.json.queryTokens||[];return false}});b(w).bind("quicksearch.ajax-error",function(a,b){if(b.url=="/labels/autocompletelabel.action?maxResults=3"){m.queryTokens=[];return false}});a.quicksearch("/labels/autocompletelabel.action?maxResults=3",function(){if(!b("#labels-autocomplete-list").find(".label-suggestion").length||a.val()==="")this.hide();else if(!e)for(var c=b("#labels-autocomplete-list").find("a.label-suggestion"),d=0;d<
c.length;d++)c.get(d).href="#"},{makeParams:function(a){return{query:a,contentId:d.params.pageId||""}},dropdownPlacement:function(a){b("#labels-autocomplete-list").append(a)},ajsDropDownOptions:{selectionHandler:function(c,d){if(d.find("a.label-suggestion").length){var f=b("span",d),f=b.data(f[0],"properties"),h=a.val(),i=[];if(e){i=h.split(/\s+/);i[i.length-1]=f.name;a.val(i.join(" "))}else{for(var j=m.queryTokens,i=-1,k,l="",n=0,o=j.length;n<o;n++){l=j[n];k=h.lastIndexOf(l);k>i&&(i=k)}if(i!==-1){j=
h.substr(0,i);(h=h.substr(i+l.length).match(/^\s+/))&&(j=j+h[0]);a.val(j+f.name)}else a.val(f.name)}}this.hide();c.preventDefault();a.focus()}}})}},labelsAreNotPersisted:l,routes:o,setLabelError:p,parseLabelStringToArray:z,getLabelLink:function(a,b){var c="/label/";a!==null&&(a!==void 0&&a!=="")&&(c=c+(a+"/"));var d=encodeURI;var f=b.prefix,h=b.name;return d(c+(f==="global"||f==="team"||f===void 0||f===""||f===null?h:f+":"+h))},setLabelsInputField:s,getLabelsInputField:t}});
require("confluence/module-exporter").exportModuleAsGlobal("confluence-labels/labels/labels","AJS.Labels");