var tinymce=null,tinyMCEPopup,tinyMCE;
tinyMCEPopup={init:function(){var a=this,b;b=a.getWin();tinymce=b.tinymce;tinyMCE=b.tinyMCE;a.editor=tinymce.EditorManager.activeEditor;a.params=a.editor.windowManager.params;a.features=a.editor.windowManager.features;a.dom=a.editor.windowManager.createInstance("tinymce.dom.DOMUtils",document);!1!==a.features.popup_css&&a.dom.loadCSS(a.features.popup_css||a.editor.settings.popup_css);a.listeners=[];a.onInit={add:function(b,d){a.listeners.push({func:b,scope:d})}};a.isWindow=!a.getWindowArg("mce_inline");
a.id=a.getWindowArg("mce_window_id");"3"===tinymce.majorVersion&&a.editor.windowManager.onOpen.dispatch(a.editor.windowManager,window)},getWin:function(){return!window.frameElement&&window.dialogArguments||opener||parent||top},getWindowArg:function(a,b){var c=this.params[a];return tinymce.is(c)?c:b},getParam:function(a,b){return this.editor.getParam(a,b)},getLang:function(a,b){return this.editor.getLang(a,b)},execCommand:function(a,b,c,d){d=d||{};d.skip_focus=1;this.restoreSelection();return this.editor.execCommand(a,
b,c,d)},resizeToInnerSize:function(){var a=this;setTimeout(function(){var b=a.dom.getViewPort(window);a.editor.windowManager.resizeBy(a.getWindowArg("mce_width")-b.w,a.getWindowArg("mce_height")-b.h,a.id||window)},10)},executeOnLoad:function(a){this.onInit.add(function(){eval(a)})},storeSelection:function(){this.editor.windowManager.bookmark=tinyMCEPopup.editor.selection.getBookmark(1)},restoreSelection:function(){var a=tinyMCEPopup;!a.isWindow&&tinymce.isIE&&a.editor.selection.moveToBookmark(a.editor.windowManager.bookmark)},
requireLangPack:function(){var a=this.getWindowArg("plugin_url")||this.getWindowArg("theme_url");a&&(this.editor.settings.language&&!1!==this.features.translate_i18n&&!1!==this.editor.settings.language_load)&&(a+="/langs/"+this.editor.settings.language+"_dlg.js",tinymce.ScriptLoader.isDone(a)||(document.write('<script type="text/javascript" src="'+tinymce._addVer(a)+'"><\/script>'),tinymce.ScriptLoader.markDone(a)))},pickColor:function(a,b){this.execCommand("mceColorPicker",!0,{color:document.getElementById(b).value,
func:function(a){document.getElementById(b).value=a;try{document.getElementById(b).onchange()}catch(d){}}})},openBrowser:function(a,b){tinyMCEPopup.restoreSelection();this.editor.execCallback("file_browser_callback",a,document.getElementById(a).value,b,window)},confirm:function(a,b,c){this.editor.windowManager.confirm(a,b,c,window)},alert:function(a,b,c){this.editor.windowManager.alert(a,b,c,window)},close:function(){function a(){b.editor.windowManager.close(window);tinymce=tinyMCE=b.editor=b.params=
b.dom=b.dom.doc=null}var b=this;tinymce.isOpera?b.getWin().setTimeout(a,0):a()},_restoreSelection:function(){var a=window.event.srcElement;"INPUT"===a.nodeName&&("submit"===a.type||"button"===a.type)&&tinyMCEPopup.restoreSelection()},_onDOMLoaded:function(){var a=tinyMCEPopup,b=document.title,c,d;if(!a.domLoaded){a.domLoaded=1;if(!1!==a.features.translate_i18n){c=document.body.innerHTML;tinymce.isIE&&(c=c.replace(/ (value|title|alt)=([^"][^\s>]+)/gi,' $1="$2"'));document.dir=a.editor.getParam("directionality",
"");if((d=a.editor.translate(c))&&d!=c)document.body.innerHTML=d;if((d=a.editor.translate(b))&&d!=b)document.title=b=d}(!a.editor.getParam("browser_preferred_colors",!1)||!a.isWindow)&&a.dom.addClass(document.body,"forceColors");document.body.style.display="";tinymce.isIE&&document.addEventListener("mouseup",tinyMCEPopup._restoreSelection,!1);a.restoreSelection();a.resizeToInnerSize();a.isWindow?window.focus():a.editor.windowManager.setTitle(window,b);!tinymce.isIE&&!a.isWindow&&tinymce.dom.Event._add(document,
"focus",function(){a.editor.windowManager.focus(a.id)});tinymce.each(a.dom.select("select"),function(a){a.onkeydown=tinyMCEPopup._accessHandler});tinymce.each(a.listeners,function(b){b.func.call(b.scope,a.editor)});a.getWindowArg("mce_auto_focus",!0)&&(window.focus(),tinymce.each(document.forms,function(b){tinymce.each(b.elements,function(b){if(a.dom.hasClass(b,"mceFocus")&&!b.disabled)return b.focus(),!1})}));document.onkeyup=tinyMCEPopup._closeWinKeyHandler}},_accessHandler:function(a){a=a||window.event;
if(13==a.keyCode||32==a.keyCode){a=a.target||a.srcElement;if(a.onchange)a.onchange();return tinymce.dom.Event.cancel(a)}},_closeWinKeyHandler:function(a){a=a||window.event;27==a.keyCode&&tinyMCEPopup.close()},_wait:function(){document.attachEvent?(document.attachEvent("onreadystatechange",function(){"complete"===document.readyState&&(document.detachEvent("onreadystatechange",arguments.callee),tinyMCEPopup._onDOMLoaded())}),document.documentElement.doScroll&&window==window.top&&function(){if(!tinyMCEPopup.domLoaded){try{document.documentElement.doScroll("left")}catch(a){setTimeout(arguments.callee,
0);return}tinyMCEPopup._onDOMLoaded()}}(),document.attachEvent("onload",tinyMCEPopup._onDOMLoaded)):document.addEventListener&&(window.addEventListener("DOMContentLoaded",tinyMCEPopup._onDOMLoaded,!1),window.addEventListener("load",tinyMCEPopup._onDOMLoaded,!1))}};tinyMCEPopup.init();tinyMCEPopup._wait();