define("confluence-quick-edit/handlers/comment","jquery ajs confluence/legacy wrm/context-path confluence-editor-loader/editor-loader confluence/api/event aui/flag confluence/api/logger confluence-editor/editor/page-editor-message confluence/message-controller confluence/meta confluence-quick-edit/captcha-manager confluence-quick-edit/handlers/page confluence-quick-edit/util".split(" "),function(f,b,i,o,p,l,t,q,e,g,c,r,s,m){function n(a,h){var b=a.match(RegExp("[?&]"+h+"=(\\d+)"));return b&&b.length>
1?parseInt(b[1],10):0}f(function(){b.AppLinksInitialisationBinder=function(a){l.bind("init.rte",a)}});var j={timeout:8E3,showLoadingEditorErrorMessage:function(a){var h={};l.trigger("rte-quick-comment-loading-failed");if(a==="READ_ONLY"){h.title=b.I18n.getText("read.only.mode.default.error.title");h.body=b.I18n.getText("read.only.mode.default.error.description")}else{h.title=b.I18n.getText("quick.comment.loading.error.message.title");h.body=b.I18n.getText("quick.comment.loading.error.message")}g.showError(h,
g.Location.FLAG)},preInitialise:function(){s.disable();c.set("content-type","comment");c.set("draft-type","");b.params.contentType="comment";b.params.draftType="";c.set("use-inline-tasks","false");f("#editor-precursor").children().eq(0).hide();f("#pagelayout-menu").parent().hide();f("#page-layout-2-group").hide();f("#rte-button-tasklist").remove();f("#pluggable-status-container").remove();f("#rte-insert-tasklist").parent().remove()},postInitialise:function(a){b.Rte.editorFocus(a.editor)},delegatingSaveCommentHandler:function(a){return a.asyncRenderSafe?
j.ajaxSaveCommentHandler(a):j.reloadPageSaveCommentHandler(a)},reloadPageSaveCommentHandler:function(a){var b=m.getBaseUrl();b.addQueryParam("focusedCommentId",a.id);b.addQueryParam("refresh",+new Date);window.location.href=b.toString()+"#comment-"+a.id},ajaxSaveCommentHandler:function(a){var b={isDefault:true,path:c.get("static-resource-url-prefix")+"/images/icons/profilepics/default.png"};c.get("current-user-avatar-uri-reference")!==o()+"/images/icons/profilepics/default.png"&&(b={isDefault:false,
path:c.get("current-user-avatar-uri-reference")});var d=c.get("remote-user"),f={userName:d===""?null:d,displayName:c.get("current-user-fullname"),profilePicture:b};j.cancelComment().done(function(){i.CommentDisplayManager.addOrUpdateComment(f,a,true,false);l.trigger("page.commentAddedOrUpdated",{commentId:a.id})})},cancelHandler:function(){var a=require("confluence-quick-edit/quick-edit");b.Rte.Content.editorResetContentChanged();a.deactivateEditor()},createCommenterParam:function(a,b,d){return{userName:b||
c.get("remote-user")||null,displayName:d||c.get("user-display-name"),profilePicture:{isDefault:a.hasClass("defaultLogo"),path:a.attr("src")}}},createSaveHandler:function(a,h){var d=m.generateUUID();return function(c){var k=require("confluence/editor-notifications");c.preventDefault();if(b.Rte.Content.isEmpty()){k.notify("warning",b.I18n.getText("content.empty"));i.Editor.UI.toggleSavebarBusy(false)}else{var k=c=0,e=p.getEditorForm();if(e.is("form")){k=e.attr("action");c=n(k,"parentId");k=n(k,"commentId")}var g=
new r(e),e=function(a,b){h(a,b);g.refreshCaptcha()},j=f("#watchPage").is(":checked");k>0?i.Editor.CommentManager.updateComment(i.getContentId(),k,b.Rte.Content.getHtml(),j,g.getCaptchaData(),a,e):i.Editor.CommentManager.saveComment(i.getContentId(),c,b.Rte.Content.getHtml(),j,d,g.getCaptchaData(),a,e)}}},saveCommentErrorHandler:function(a,c){var d;i.Editor.UI.toggleSavebarBusy(false);if(a&&a.search(/captcha/i)!==-1){d=b.I18n.getText("captcha.response.failed");e.closeMessages(["captcha-response-failed"]);
e.handleMessage("captcha-response-failed",{type:"error",message:d})}else if(a&&a.search(/Unsupported character found in content: (.{12})/i)!==-1){d=JSON.parse(a.replace(/error: {2}- /,"")).message.split("Unsupported character found in content: ")[1];d=b.I18n.getText("quick.comment.mysql.utf8.content.validation.failed.message",d);e.closeMessages(["utf8-validation-failed"]);e.handleMessage("utf8-validation-failed",{title:b.I18n.getText("mysql.utf8.content.validation.failed.title"),type:"error",message:d})}else{d=
b.I18n.getText("quick.comment.saving.error.message");if(c)g.showError(g.parseError(c,d),g.Location.FLAG);else{e.closeMessages(["server-offline"]);e.handleMessage("server-offline",{type:"error",message:d})}}q.logError("Error saving comment",a)},cancelComment:function(){b.Rte.Content.editorResetContentChanged();return require("confluence-quick-edit/quick-edit").deactivateEditor()},proceedWithActivation:function(){var a=new f.Deferred,c=b.Rte&&b.Rte.getEditor();if(c){if(c.isDirty()&&!i.Editor.isEmpty()&&
!confirm(b.I18n.getText("unsaved.comment.lost")))return a.reject();a=j.cancelComment()}else a.resolve();return a}};return j});require("confluence/module-exporter").exportModuleAsGlobal("confluence-quick-edit/handlers/comment","AJS.Confluence.QuickEdit.QuickComment");