define("confluence-editor/tinymce3/plugins/confcursortarget/editor_plugin_src",["jquery","ajs","tinymce","confluence/meta"],function(d,f,h,k){var l=".wysiwyg-macro,.placeholder,table";return{cursorTarget:{addFixSelector:function(d){l+=","+d}},cursorTargetPlugin:{init:function(e){function o(a,b){d(l,a).each(function(a,m){var e=function(a){if(0===a.length)throw Error("no paragraph element specified");y()&&a.addClass("auto-cursor-target");a=a[0];0===a.childNodes.length&&(a.innerHTML="<br />");return a},
f=function(a,b){var c=d("<p/>");if(d(a.parentNode).is("li, td, th"))for(;a[b]&&!d(a[b]).is(u);)c["previousSibling"==b?"prepend":"append"](a[b]);return e(c)},g=d(m);(!g.prev().length||g.prev(l).length||d(m.parentNode).is("li, td, th")&&!d(m.previousSibling).is(u))&&g.before(f(m,"previousSibling"));(!g.next().length||g.next(".synchrony-container").length||d(m.parentNode).is("li, td, th")&&!d(m.nextSibling).is(u))&&g.after(f(m,"nextSibling"));y()&&g.next().length&&(!g.next().next().length&&p(g.next()[0]))&&
g.next().addClass("auto-cursor-target");if(b){var f=function(a){("BR"===a[0].nodeName||p(a[0]))&&a.replaceWith(e(d("<p/>")))},i=g.prev(),j;if(j=i.length)a:{for(j=i.prev();j.length&&!j.is(l);){var h=j[0];if("BR"!==h.nodeName&&"P"!==h.nodeName){j=!1;break a}j=j.prev()}j=!0}j&&f(i);g=g.next();if(i=g.length)a:{for(i=g.next();i.length&&!i.is(l);){j=i[0];if("BR"!==j.nodeName&&"P"!==j.nodeName){i=!1;break a}i=i.next()}i=!0}i&&f(g)}})}function y(){return k.getBoolean("shared-drafts")&&"limited"!==k.get("edit-mode")&&
("page"===k.get("content-type")||"blogpost"===k.get("content-type"))}function z(a){d("p",a).each(function(a,c){p(c)&&q(c)&&d(c).attr("data-tag","marked-for-deletion")});d("p[data-tag=marked-for-deletion]",a).remove();return a}function p(a){function b(a){for(var b=0,d=0,e=0,g=a.childNodes.length;e<g;e++){var f=a.childNodes[e];if("BR"===f.nodeName){if(1<++b)return!1}else if(/^[\s|\u00A0]$/.test(f.nodeValue)){if(1<++d)return!1}else if(""!==f.nodeValue)return!1}return!0}return 1===a.nodeType&&0===a.childNodes.length||
b(a)}function q(a){if(!a||1!==a.nodeType)return!1;var b=r(a,!1),c=r(a,!0),a=t(b)||d(b).is(l),e=t(c)||d(c).is(l),b=t(b)&&t(c);return a&&e&&!b}function t(a){return!a?!0:a.className&&/cell|header|footer/.test(a.className)}function r(a,b){var c=d(a);do{var e=b?c[0].nextSibling:c[0].previousSibling;if(e)return e;c=c.parent()}while(0<c.length&&!c.is(".cell, .mceContentBody, td, li"));return null}function v(a){var b=a.startContainer;return 3===b.nodeType?!(b.previousSibling&&(3===b.previousSibling.nodeType||
d(b.previousSibling).is("br")))&&0===a.startOffset:1===b.nodeType?0===a.startOffset:!1}function A(a){var a=d(a).children(),b;for(b=0;b<a.length;b++)if(!p(a[b])&&(d(a[b]).contents().filter(function(){return 3===this.nodeType}).length||A(a[b])))return!0;return!1}function w(a,b){var c;if(c=b.startContainer===b.endContainer)if(c=1===b.startContainer.nodeType)c=b.startOffset,a||c--,c=0<=c&&c<b.startContainer.childNodes.length&&"TABLE"===b.startContainer.childNodes[c].nodeName;return c}function B(a){if(!a.collapsed)return!1;
var b=a.startContainer,c;if(3===b.nodeType)return c=r(b,!0),a.startOffset===b.nodeValue.length&&(null==c||d(c).is("br"));if(1===b.nodeType){if(d(b).is("td, th")&&0===a.startOffset&&0<b.childNodes.length)return d(b.childNodes[0]).is("br");c=r(b.parentNode.childNodes[0===a.startOffset?0:a.startOffset-1],!0);return null==c||d(c).is("br")}return!1}function C(a){return a&&1===a.childNodes.length&&d(a.childNodes[0]).is("br")}function D(a,b){return h.isWebKit&&w(!1,b)||h.isGecko&&(B(b)||q(a)&&0===b.startOffset&&
C(a))?!0:!1}function E(a,b){var c;if(c=h.isWebKit)if(!(c=w(!0,b)))if(!(c=v(b)&&q(a)))c=e.getBody(),c=c.childNodes.length?b.collapsed&&0===b.startOffset&&c.childNodes[0]===b.startContainer:!1;return c||h.isGecko&&v(b)&&q(a)&&C(a)?!0:!1}function x(a,b){var c=b.keyCode;if(c!==n.BACKSPACE&&c!==n.DELETE)return!0;a.selection.isCollapsed()?c===n.BACKSPACE&&E(a.selection.getNode(),a.selection.getRng(F))?h.dom.Event.prevent(b):c===n.DELETE&&D(a.selection.getNode(),a.selection.getRng(F))&&h.dom.Event.prevent(b):
o(a.getBody());return!0}var F=!0,u="ol, ul, p, pre, table, blockquote, div, h1, h2, h3, h4, h5, h6",n=d.ui.keyCode,s=function(){o(e.getBody(),!0)},G=function(a){o(a,!1);h.isIE10&&d("p, td.confluenceTd, th.confluenceTh",a).each(function(a,c){c&&""===c.innerHTML&&d(c).html("<br />")})};k.get("shared-drafts")&&("page"===k.get("content-type")||"blog"===k.get("content-type"))&&"collaborative"===k.get("edit-mode")?f.bind("cursor-target-refresh",function(){G(e.getBody())}):(e.onSetContent.add(function(a){o(a.getBody());
var a=a.getBody(),b=h.isIE?"&nbsp;":"<br/>";d("p, td.confluenceTd, th.confluenceTh",a).each(function(a,e){e&&(e.childNodes&&1===e.childNodes.length&&3===e.childNodes[0].nodeType&&e.childNodes[0].nodeValue&&1===e.childNodes[0].nodeValue.length&&160===e.childNodes[0].nodeValue.charCodeAt(0))&&d(e).html(b)})}),e.onGetContent.add(function(a,b){var c=z(d("<div class='root-node'>"+b.content+"</div>")),c=f.Rte.getEditor().serializer.serialize(c[0],b);b.content=c.substring(23,c.length-6)}),e.onInit.add(function(){e.selection.onSetContent.add(s);
e.dom.bind(e.getBody(),"cut",s);f.bind("cursor-target-refresh",s)}),e.onRemove.add(function(){f.unbind("cursor-target-refresh",s)}),h.isGecko&&e.onKeyDown.add(function(a,b){(b.keyCode===n.ENTER||b.keyCode===n.BACKSPACE||b.keyCode===n.DELETE)&&a.selection.normalize()}),e.onKeyDown.add(x),e.onKeyUp.add(x),h.isGecko&&e.onKeyPress.add(x),e.onPaste.add(s));d.extend(this,{isCursorBeforeAfterTable:w,isCursorTarget:q,_isTextContainerEmpty:p,_processCursorTargets:z,_isCursorAtStartOfContainer:v,_isCursorAtEndOfContainer:function(a){var b=
a.startContainer;if(b.nodeType===3)return!(b.nextSibling&&(b.nextSibling.nodeType===3||d(b.nextSibling).is("br")))&&a.endOffset===b.nodeValue.length;if(b.nodeType===1){var c=b.childNodes[a.startOffset];return d(c).is("br")&&c.nextSibling==null?true:a.endOffset===b.childNodes.length}return false},_getSiblingWithinBlockDisregardingNesting:r,_doesContainerHaveNestedContent:A,_addCursorTargetParagraphsToContent:o,_isCursorAtEndOfBottomRightCellInTable:B,_shouldCancelDelete:D,_shouldCancelBackspace:E,
_collabEditingCursorTargetRefresh:G});f.Rte.Cursor=f.Rte.Cursor||{};d.extend(f.Rte.Cursor,{isTextContainerEmpty:p,fixCursorTargets:o})},getInfo:function(){return{longname:"Cursor Target plugin",author:"Atlassian",authorurl:"http://www.atlassian.com",version:"1.0"}}}}});
require("confluence/module-exporter").safeRequire("confluence-editor/tinymce3/plugins/confcursortarget/editor_plugin_src",function(d){require("confluence/module-exporter").namespace("AJS.Rte.CursorTarget",d.cursorTarget);var f=require("tinymce");f.create("tinymce.plugins.CursorTargetPlugin",d.cursorTargetPlugin);f.PluginManager.add("cursorTarget",f.plugins.CursorTargetPlugin)});