define("confluence-editor/tinymce3/plugins/confcursortarget/editor_plugin_src",["jquery","ajs","tinymce","confluence/meta"],function(d,f,i,s){var k=".wysiwyg-macro,.placeholder,table";return{cursorTarget:{addFixSelector:function(d){k+=","+d}},cursorTargetPlugin:{init:function(e){function n(a,b){d(k,a).each(function(a,l){var f=function(a){if(0===a.length)throw Error("no paragraph element specified");y()&&a.addClass("auto-cursor-target");a=a[0];0===a.childNodes.length&&(a.innerHTML="<br />");return a},
e=function(a,b){var c=d("<p/>");if(d(a.parentNode).is("li, td, th"))for(;a[b]&&!d(a[b]).is(u);)c["previousSibling"==b?"prepend":"append"](a[b]);return f(c)},h=d(l);(!h.prev().length||h.prev(k).length||d(l.parentNode).is("li, td, th")&&!d(l.previousSibling).is(u))&&h.before(e(l,"previousSibling"));(!h.next().length||h.next(".synchrony-container").length||d(l.parentNode).is("li, td, th")&&!d(l.nextSibling).is(u))&&h.after(e(l,"nextSibling"));y()&&h.next().length&&(!h.next().next().length&&o(h.next()[0]))&&
h.next().addClass("auto-cursor-target");if(b){var e=function(a){("BR"===a[0].nodeName||o(a[0]))&&a.replaceWith(f(d("<p/>")))},g=h.prev(),j;if(j=g.length)a:{for(j=g.prev();j.length&&!j.is(k);){var i=j[0];if("BR"!==i.nodeName&&"P"!==i.nodeName){j=!1;break a}j=j.prev()}j=!0}j&&e(g);h=h.next();if(g=h.length)a:{for(g=h.next();g.length&&!g.is(k);){j=g[0];if("BR"!==j.nodeName&&"P"!==j.nodeName){g=!1;break a}g=g.next()}g=!0}g&&e(h)}})}function y(){return s.getBoolean("shared-drafts")&&"limited"!==s.get("edit-mode")&&
("page"===s.get("content-type")||"blogpost"===s.get("content-type"))}function z(a){d("p",a).each(function(a,c){o(c)&&p(c)&&d(c).attr("data-tag","marked-for-deletion")});d("p[data-tag=marked-for-deletion]",a).remove();return a}function o(a){function b(a){for(var b=0,d=0,e=0,f=a.childNodes.length;e<f;e++){var g=a.childNodes[e];if("BR"===g.nodeName){if(1<++b)return!1}else if(/^[\s|\u00A0]$/.test(g.nodeValue)){if(1<++d)return!1}else if(""!==g.nodeValue)return!1}return!0}return 1===a.nodeType&&0===a.childNodes.length||
b(a)}function p(a){if(!a||1!==a.nodeType)return!1;var b=q(a,!1),c=q(a,!0),a=t(b)||d(b).is(k),e=t(c)||d(c).is(k),b=t(b)&&t(c);return a&&e&&!b}function t(a){return a?a.className&&/cell|header|footer/.test(a.className):!0}function q(a,b){var c=d(a);do{var e=b?c[0].nextSibling:c[0].previousSibling;if(e)return e;c=c.parent()}while(0<c.length&&!c.is(".cell, .mceContentBody, td, li"));return null}function v(a){var b=a.startContainer;return 3===b.nodeType?!(b.previousSibling&&(3===b.previousSibling.nodeType||
d(b.previousSibling).is("br")))&&0===a.startOffset:1===b.nodeType?0===a.startOffset:!1}function A(a){var a=d(a).children(),b;for(b=0;b<a.length;b++)if(!o(a[b])&&(d(a[b]).contents().filter(function(){return 3===this.nodeType}).length||A(a[b])))return!0;return!1}function w(a,b){var c;if(c=b.startContainer==b.endContainer)if(c=1===b.startContainer.nodeType)c=b.startOffset,a||c--,c=0<=c&&c<b.startContainer.childNodes.length&&"TABLE"===b.startContainer.childNodes[c].nodeName;return c}function B(a){if(!a.collapsed)return!1;
var b=a.startContainer,c;if(3===b.nodeType)return c=q(b,!0),a.startOffset==b.nodeValue.length&&(null==c||d(c).is("br"));if(1===b.nodeType){if(d(b).is("td, th")&&0===a.startOffset&&0<b.childNodes.length)return d(b.childNodes[0]).is("br");c=q(b.parentNode.childNodes[0===a.startOffset?0:a.startOffset-1],!0);return null==c||d(c).is("br")}return!1}function C(a){return a&&1===a.childNodes.length&&d(a.childNodes[0]).is("br")}function D(a,b){return i.isWebKit&&w(!1,b)||i.isGecko&&(B(b)||p(a)&&0===b.startOffset&&
C(a))?!0:!1}function E(a,b){var c;if(c=i.isWebKit)if(!(c=w(!0,b)))if(!(c=v(b)&&p(a)))c=e.getBody(),c=c.childNodes.length?b.collapsed&&0===b.startOffset&&c.childNodes[0]==b.startContainer:!1;return c||i.isGecko&&v(b)&&p(a)&&C(a)?!0:!1}function x(a,b){var c=b.keyCode;if(c!==m.BACKSPACE&&c!==m.DELETE)return!0;a.selection.isCollapsed()?c===m.BACKSPACE&&E(a.selection.getNode(),a.selection.getRng(F))?i.dom.Event.prevent(b):c===m.DELETE&&D(a.selection.getNode(),a.selection.getRng(F))&&i.dom.Event.prevent(b):
n(a.getBody());return!0}var F=!0,u="ol, ul, p, pre, table, blockquote, div, h1, h2, h3, h4, h5, h6",m=d.ui.keyCode,r=function(){n(e.getBody(),!0)},G=function(a){n(a,!1);i.isIE10&&d("p, td.confluenceTd, th.confluenceTh",a).each(function(a,c){c&&""===c.innerHTML&&d(c).html("<br />")})};f.Meta.get("shared-drafts")&&("page"===f.Meta.get("content-type")||"blog"===f.Meta.get("content-type"))&&"collaborative"===f.Meta.get("edit-mode")?f.bind("cursor-target-refresh",function(){G(e.getBody())}):(e.onSetContent.add(function(a){n(a.getBody());
var a=a.getBody(),b=i.isIE?"&nbsp;":"<br/>";d("p, td.confluenceTd, th.confluenceTh",a).each(function(a,e){e&&(e.childNodes&&1===e.childNodes.length&&3===e.childNodes[0].nodeType&&e.childNodes[0].nodeValue&&1===e.childNodes[0].nodeValue.length&&160===e.childNodes[0].nodeValue.charCodeAt(0))&&d(e).html(b)})}),e.onGetContent.add(function(a,b){var c=z(d("<div class='root-node'>"+b.content+"</div>")),c=f.Rte.getEditor().serializer.serialize(c[0],b);b.content=c.substring(23,c.length-6)}),e.onInit.add(function(){e.selection.onSetContent.add(r);
e.dom.bind(e.getBody(),"cut",r);f.bind("cursor-target-refresh",r)}),e.onRemove.add(function(){f.unbind("cursor-target-refresh",r)}),i.isGecko&&e.onKeyDown.add(function(a,b){(b.keyCode===m.ENTER||b.keyCode===m.BACKSPACE||b.keyCode===m.DELETE)&&a.selection.normalize()}),e.onKeyDown.add(x),e.onKeyUp.add(x),i.isGecko&&e.onKeyPress.add(x),e.onPaste.add(r));d.extend(this,{isCursorBeforeAfterTable:w,isCursorTarget:p,_isTextContainerEmpty:o,_processCursorTargets:z,_isCursorAtStartOfContainer:v,_isCursorAtEndOfContainer:function(a){var b=
a.startContainer;if(b.nodeType===3)return!(b.nextSibling&&(b.nextSibling.nodeType===3||d(b.nextSibling).is("br")))&&a.endOffset==b.nodeValue.length;if(b.nodeType===1){var c=b.childNodes[a.startOffset];return d(c).is("br")&&c.nextSibling==null?true:a.endOffset==b.childNodes.length}return false},_getSiblingWithinBlockDisregardingNesting:q,_doesContainerHaveNestedContent:A,_addCursorTargetParagraphsToContent:n,_isCursorAtEndOfBottomRightCellInTable:B,_shouldCancelDelete:D,_shouldCancelBackspace:E,_collabEditingCursorTargetRefresh:G});
f.Rte.Cursor=f.Rte.Cursor||{};d.extend(f.Rte.Cursor,{isTextContainerEmpty:o,fixCursorTargets:n})},getInfo:function(){return{longname:"Cursor Target plugin",author:"Atlassian",authorurl:"http://www.atlassian.com",version:"1.0"}}}}});
require("confluence/module-exporter").safeRequire("confluence-editor/tinymce3/plugins/confcursortarget/editor_plugin_src",function(d){require("confluence/module-exporter").namespace("AJS.Rte.CursorTarget",d.cursorTarget);var f=require("tinymce");f.create("tinymce.plugins.CursorTargetPlugin",d.cursorTargetPlugin);f.PluginManager.add("cursorTarget",f.plugins.CursorTargetPlugin)});