require("ajs jquery confluence-drag-and-drop/analytics/files-upload-analytics confluence-drag-and-drop/drag-and-drop-overlay document confluence/message-controller".split(" "),function(a,s,p,q,m,n){a.toInit(function(i){var e,r=/^\w+:\/\/[^\/?#]+/.exec(location.href),o=false;a.Rte.BootstrapManager.addOnInitCallback(function(){var j=a.Rte.getEditor().getBody().parentNode,k=m.getElementById("fileuploadShim"),l=false;if(!k){k=m.createElement("div");k.setAttribute("id","fileuploadShim");m.body.appendChild(k)}i.browser.mozilla&&
i.browser.version.indexOf("1.9.2")>-1&&j.addEventListener("drop",function(a){a.stopPropagation()},false);var c=new plupload.Uploader({runtimes:"html5",dragdrop:true,drop_element:j,browse_button:k.getAttribute("id"),multipart:false,max_file_size:+a.Meta.get("global-settings-attachment-max-size")});e||(e=new a.DragAndDropProgressDialog);c.init();c.bind("Started",function(a,b){p.triggerEvent("confluence.editor.files.drag-and-drop",b)});c.bind("FilesAdded",function(h,b){a.UploadUtils.filterFiles(h,b,
function(a,b){for(var d=0;d<b.length;d++){var h=b[d];h.status!==plupload.FAILED&&e.render({workId:h.id,status:h.status,file:h})}c.start()})});c.bind("BeforeUpload",function(h,b){if(a.Meta.get("content-type")==="template"){h.stop();if(!o){var g=new a.Dialog(450,180);g.addHeader(a.I18n.getText("dnd.templates.not.supported.heading"));g.addSubmit(a.I18n.getText("dnd.templates.not.supported.ok"),function(){g.remove()});g.addPanel("Panel 1","panel1");g.getCurrentPanel().html(a.I18n.getText("dnd.templates.not.supported.message"));
g.show();o=true}}else{var f=r+a.contextPath()+"/plugins/drag-and-drop/upload.action",d={},c=a.Meta.get("page-id");if(c)d.pageId=c;var i=a.Meta.get("draft-id");if(c==0&&i>0)d.draftId=i;if(c=a.Meta.get("drag-and-drop-entity-id"))d.dragAndDropEntityId=c;c=b.name.substr(b.name.lastIndexOf(".")+1);d.filename=b.name;d.size=b.size;d.minorEdit=true;d.spaceKey=a.Meta.get("space-key")||"";d.mimeType=plupload.mimeTypes[c.toLowerCase()]||a.DragAndDropUtils.defaultMimeType;d.atl_token=a.Meta.get("atl-token");
d.contentType=a.Meta.get("content-type");d.isVFMSupported=!!a.MacroBrowser.getMacroMetadata("view-file");h.settings.url=plupload.buildUrl(f,d);e.cancelListeners.push(function(b,c){var d=h.getFile(c.workId);d&&h.removeFile(d);e.renderInfo(c.workId,a.I18n.getText("dnd.upload.file.removed.from.queue"))});e.show()}});c.bind("UploadProgress",function(a,b){e.renderUpdateToBytesUploaded(b.id,b.loaded,b.size);e.hideCloseButton()});i.browser.mozilla&&plupload.addEvent(j,"dragenter",function(a){l=a.rangeParent&&
a.rangeOffset!==void 0?{startElement:a.rangeParent,startOffset:a.rangeOffset}:false});c.bind("FileUploaded",function(c,b,g){if(g.status){if(g.response)try{var f=i.parseJSON(g.response);l&&i(l.startElement.parentNode).closest('[contenteditable="true"]',j).length&&tinymce.activeEditor.selection.setCursorLocation(l.startElement,l.startOffset);f.htmlForEditor.substr(0,4)==="<img"?tinymce.confluence.ImageUtils.insertImagePlaceholder(f.htmlForEditor):a.Rte.getEditor().execCommand("mceInsertContent",false,
f.htmlForEditor,{skip_focus:true})}catch(d){a.log("FileUploaded threw an exception "+d)}e.renderComplete(b.id)}else e.renderError(b.id,a.I18n.getText("dnd.error.server.not.responding"))});c.bind("Error",function(c,b){var g,f="";if(b.response){try{g=JSON.parse(b.response);f=g.actionErrors[0]}catch(d){f=d.name==="SyntaxError"?a.I18n.getText("dnd.error.invalid.response.from.server"):n.parseError(b.xhr,b.message)}e.renderError(b.file.id,f);a.trigger("analyticsEvent",{name:"confluence.editor.upload.error.server-unknown"})}else if(b.message){f=
b.message;if(b.code===plupload.FILE_SIZE_ERROR){f=a.I18n.getText("dnd.validation.file.too.large",a.DragAndDropUtils.niceSize(a.Meta.get("global-settings-attachment-max-size")));a.trigger("analyticsEvent",{name:"confluence.editor.upload.error.file-size"})}else if(b.code===a.UploadUtils.ErrorCode.FILE_IS_A_FOLDER_ERROR){f=a.I18n.getText("dnd.validation.file.type.not.supported");a.trigger("analyticsEvent",{name:"confluence.editor.upload.error.file-type"})}e.render({workId:b.file.id,status:b.file.status,
file:b.file,errorMessage:f});if(!e.isVisible()){e.show();e.showCloseButton()}}else{f=n.parseError(b.xhr);e.renderError(b.file.id,f);a.trigger("analyticsEvent",{name:"confluence.editor.upload.error.server-unknown"})}});c.bind("UploadComplete",function(){if(!c.total.queued){c.stop();e.showCloseButton();e.hasErrors()||setTimeout(function(){e.hide();e.clearRenderOutput();a.Rte.BookmarkManager.restoreBookmark()},1E3)}});a.Confluence.Uploader=c;a.Confluence.EditorUploadProgressDialog=e;q.bindFileDragOverlay({$dragZone:i(j).add("#toolbar ~ #editor-precursor"),
$overlayZone:i("#rte"),isTransparent:true})})})});