define("confluence-editor/tinymceplugin/auiwindowmanager","ajs tinymce jquery raphael window confluence/api/constants".split(" "),function(h,g,e,k,l,m){var i=g.util.Dispatcher,j=g.isIE;return{AUIWindowManager:{init:function(a){a.onBeforeRenderUI.add(function(){a.windowManager=new g.AUIWindowManager(a)})},getInfo:function(){return{longname:"AUIWindowManager",author:"Atlassian",authorurl:"http://www.atlassian.com",version:g.majorVersion+"."+g.minorVersion}}},WindowManager:{AUIWindowManager:function(a){this.editor=
a;this.onOpen=new i(this);this.onClose=new i(this);this.params={};this.features={};this.modalDialogsStack=[];this.dialogs={};this.count=0},open:function(a,c){a=a||{};this.initialiseSettings(a);c=c||{};c=this.setDefaultParameters(c);c.mce_width=a.width;c.mce_height=a.height;c.mce_auto_focus=a.auto_focus;if(j){a.center=true;a.help=false;a.dialogWidth=a.width+"px";a.dialogHeight=a.height+"px"}this.features=a;this.params=c;this.onOpen.dispatch(this,a,c);var b=a.height;a.name&&(b=b+56);if(c.cancelLink||
c.buttons)b=b+51;b=b+40;a.popup&&(b=b+8);var d=a.id||g.DOM.uniqueId(),f=new h.ConfluenceDialog({width:a.width,height:b,id:d,onCancel:function(){f.hide().remove()}});a.name&&f.addHeader(this.editor.getLang(a.name));this.createDialogButtons(f,c,d);a.file=a.file||a.url;if(a.file)a.file=g._addVer(a.file);this.createDialogContent(f,a,c,d);c.helpLink&&this.createHelpLink(f,c.helpLink,c.helpName,d);c.hintText&&this.createHintText(f,c.hintText,d);b={id:d,settings:a,params:c,dialog:f};this.modalDialogsStack.push(b);
this.dialogs[d]=b;this.count++;h.Rte.BookmarkManager.storeBookmark();f.show();f.takeFocus!==void 0&&f.takeFocus();if(j){e("#"+d).css("overflow","hidden");e("#"+d+" ."+c.cssClass).css("overflow","hidden")}return d},initialiseSettings:function(a){a.width=parseInt(a.width||400,10);a.height=parseInt(a.height||250,10);a.resizable=false;if(a.popup===void 0)a.popup=true;if(a.popup&&a.content!==void 0)a.popup=false;a.scrollbars=a.scrollbars?"yes":"no"},createDialogButtons:function(a,c,b){if(c.buttons)for(var d=
0,d=0;d<c.buttons.length;d++){var e=c.buttons[d];a.addButton(this.editor.getLang(e.label),e.action)}c.cancelLink&&a.addCancel(this.editor.getLang("auiwindowmanager.cancel"),function(){return g.activeEditor.windowManager.close(b)})},createDialogContent:function(a,c,b,d){var f=this.createContentId(d),d="panel_"+f;if(c.popup){a.addPanel(d,e("<iframe id='"+f+"' width='100%' height='"+c.height+"px' frameborder='0' name='auidialogiframe' src='"+c.file+"' scrolling='"+c.scrollbars+"'></iframe>"),b.cssClass);
a.takeFocus=function(){e("#"+f).focus()}}else{if(c.content==void 0){a.addPanel(d,e("<div id='"+f+"'/>"),b.cssClass);e("#"+f).load(c.file)}else a.addPanel(d,e("<div id='"+f+"'>"+c.content+"</div>"),b.cssClass);a.takeFocus=function(){var a=e("#"+f+" :input");if(a.length)e(a[0]).focus();else{a=e("#"+f+" .button-panel button");a.length&&e(a[0]).focus()}}}a.gotoPanel(0,0)},createHintText:function(a,c,b){a=e("<div></div>").addClass("dialog-tip");a.text(g.activeEditor.getLang(c));e("#"+b+" .dialog-button-panel").append(a)},
createHelpLink:function(a,c,b,d){a=e("<div></div>").addClass("dialog-help-link");a.load(m.CONTEXT_PATH+"/plugins/tinymce/helplink.action",{linkUrlKey:c,linkNameKey:b||""});e("#"+d+" .dialog-components .dialog-title").prepend(a)},close:function(a,c){var b,d;if(typeof a==="string")b=a;else if(c)b=c;else if(d=this.modalDialogsStack.pop())b=d.id;if(this.dialogs[b]){this.count--;d=this.dialogs[b];d.dialog.remove();this.dialogs[b]=null;g.activeEditor.focus();h.Rte.BookmarkManager.restoreBookmark()}else h.log("Couldn't find id "+
b+" in dialogs array so dialog is not closed.");return false},alert:function(a,c,b){var d;d=this.open({content:"<p>"+a+"</p>",width:500,height:160,popup:false},{buttons:[{label:"auiwindowmanager.ok",action:function(){g.activeEditor.windowManager.toggleOtherDialogs(d,true);g.activeEditor.windowManager.close(d);c&&c.call(b||this)}}],cancelLink:false,cssClass:"tinymce-auidialog-alert"});this.toggleOtherDialogs(d,false)},createInstance:function(a,c,b,d,e,h){return new (g.resolve(a))(c,b,d,e,h)},toggleOtherDialogs:function(a,
c){for(var b=0,b=0;b<this.modalDialogsStack.length;b++){var d=this.modalDialogsStack[b];d.id!==a&&e("#"+d.id+" .dialog-button-panel").toggle(c)}},confirm:function(a,c,b,d){d=d||l;c.call(b||this,d.confirm(this._decode(this.editor.getLang(a,a))))},setBusy:function(a,c){if(this.dialogs[a])if(c){var b,d;b=this.createContentId(a);b=e("#"+b);b.hide();var f=b.parent();b=this.createBusyContentId(a);d=e("#"+b,f);if(!d.length){f.append(e("<div id='"+b+"' class='spinner'></div>"));d=e("#"+b,f);k.spinner(d[0],
50,"#666")}e(".button-panel button",e("#"+a)).each(function(a,b){e(b).prop("disabled",true)});e(d[0]).show()}else{b=this.createBusyContentId(a);d=e("#"+b);d.length&&e(d[0]).hide();b=this.createContentId(a);b=e("#"+b);e(".button-panel button",e("#"+a)).each(function(a,b){e(b).prop("disabled",false)});e(b[0]).show()}},logMCESelection:function(a){var c=g.activeEditor.selection;h.log("******************************");h.log("Logging TinyMCE selection title:    "+a);h.log("Bookmark:");h.log(c.getBookmark());
a=e(c.getRng().startContainer).text()||e(c.getRng().startContainer.parentNode).text();h.log("Range: "+a);h.log(c.getRng())},setDefaultParameters:function(a){a.inline=false;if(!a.cssClass)a.cssClass="tinymce-auidialog";if(a.cancelLink!=false)a.cancelLink=true;return a},createContentId:function(a){return"content_"+a},createBusyContentId:function(a){return"content_busy_"+a}}}});
require("confluence/module-exporter").safeRequire("confluence-editor/tinymceplugin/auiwindowmanager",function(h){var g=require("tinymce");g.create("tinymce.plugins.AUIWindowManager",h.AUIWindowManager);g.create("tinymce.AUIWindowManager:tinymce.WindowManager",h.WindowManager);g.PluginManager.add("auiwindowmanager",g.plugins.AUIWindowManager)});